### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by thomaspeitz** [aezell/mutemeet#2]
Hey chrome heroes,

i just modified your script to just switch to my google meet chrome tab and shared it in a gist (with a link to your repository)
https://gist.github.com/thomaspeitz/c72c493140c0eec44d01254fe14fad6d as i just deleted a line.

In case that was not okay, I of course delete it again.

Greetings and very thankful, Thomas

**Comment by aezell** [comment]
I've now added a LICENSE file. Thanks for the nudge.
